import type { TravelProfile, TravelRegionId } from "./types";

export const TRAVEL: Record<TravelRegionId, TravelProfile> = {
  kr: {
    id: "kr",
    city: "서울",
    country: "대한민국",
    officialEew: "strong",
    officialLabel: "기상청 현장경보·조기경보",
    embassyQuality: "detail",
    crowdWeight: 0.35,
    actionLang: "ko",
    hint: "국가 망이 조밀합니다. 워치는 문자가 오기 전 ‘방금 그거’를 먼저 가릅니다.",
  },
  jp: {
    id: "jp",
    city: "오사카",
    country: "일본",
    officialEew: "strong",
    officialLabel: "기상청 긴급지진속보 (JMA)",
    embassyQuality: "caution-only",
    crowdWeight: 0.4,
    actionLang: "ja",
    hint: "속보는 빠르지만 한국어 세부가 없습니다. 대사관은 주의 문자 수준입니다.",
  },
  tw: {
    id: "tw",
    city: "타이베이",
    country: "대만",
    officialEew: "moderate",
    officialLabel: "중앙기상서 (CWA)",
    embassyQuality: "caution-only",
    crowdWeight: 0.55,
    actionLang: "en",
    hint: "공식 경보는 있으나 여행자 언어가 빈약합니다. 파면·대피는 워치가 담당합니다.",
  },
  np: {
    id: "np",
    city: "카트만두",
    country: "네팔",
    officialEew: "none",
    officialLabel: "국가 조기경보 없음",
    embassyQuality: "slow",
    crowdWeight: 0.9,
    actionLang: "en",
    hint: "공식 알림을 기다리면 늦습니다. 군중 감지 비중을 최대로 올립니다.",
  },
  tr: {
    id: "tr",
    city: "이스탄불",
    country: "튀르키예",
    officialEew: "weak",
    officialLabel: "AFAD (지역 편차 큼)",
    embassyQuality: "slow",
    crowdWeight: 0.75,
    actionLang: "en",
    hint: "강진 이력이 큽니다. 로컬 망이 비면 손목 판별과 가족 밴드가 먼저입니다.",
  },
  "us-west": {
    id: "us-west",
    city: "로스앤젤레스",
    country: "미국",
    officialEew: "strong",
    officialLabel: "USGS ShakeAlert",
    embassyQuality: "detail",
    crowdWeight: 0.4,
    actionLang: "en",
    hint: "안드로이드는 Google이 커버합니다. 아이폰·워치 공백을 이 앱이 메웁니다.",
  },
  mx: {
    id: "mx",
    city: "멕시코시티",
    country: "멕시코",
    officialEew: "moderate",
    officialLabel: "SASMEX",
    embassyQuality: "caution-only",
    crowdWeight: 0.6,
    actionLang: "en",
    hint: "분지 지반이 흔들림을 키웁니다. 건물 필터가 고층 장주기를 학습합니다.",
  },
};

export const TRAVEL_LIST = Object.values(TRAVEL);
