/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EvacuateRouteImport } from './routes/evacuate'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as LogRouteImport } from './routes/log'
import { Route as MapRouteImport } from './routes/map'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuakeIdRouteImport } from './routes/quake.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuateRoute = EvacuateRouteImport.update({
  id: '/evacuate',
  path: '/evacuate',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuakeIdRoute = QuakeIdRouteImport.update({
  id: '/quake/$id',
  path: '/quake/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/evacuate': typeof EvacuateRoute
  '/family': typeof FamilyRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/quake/$id': typeof QuakeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/evacuate': typeof EvacuateRoute
  '/family': typeof FamilyRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/quake/$id': typeof QuakeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/evacuate': typeof EvacuateRoute
  '/family': typeof FamilyRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/quake/$id': typeof QuakeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/evacuate'
    | '/family'
    | '/log'
    | '/map'
    | '/safety'
    | '/settings'
    | '/quake/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/evacuate'
    | '/family'
    | '/log'
    | '/map'
    | '/safety'
    | '/settings'
    | '/quake/$id'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/evacuate'
    | '/family'
    | '/log'
    | '/map'
    | '/safety'
    | '/settings'
    | '/quake/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  EvacuateRoute: typeof EvacuateRoute
  FamilyRoute: typeof FamilyRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  QuakeIdRoute: typeof QuakeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuate': {
      id: '/evacuate'
      path: '/evacuate'
      fullPath: '/evacuate'
      preLoaderRoute: typeof EvacuateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quake/$id': {
      id: '/quake/$id'
      path: '/quake/$id'
      fullPath: '/quake/$id'
      preLoaderRoute: typeof QuakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  EvacuateRoute: EvacuateRoute,
  FamilyRoute: FamilyRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  QuakeIdRoute: QuakeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
